parameters:
  fos_message.pagination_limit: 10

services:
  _defaults:
    autowire: true
    autoconfigure: true

  FOS\MessageBundle\Repository\:
    resource: '../../Repository'
    
  fos_message.inbox.controller:
    class: FOS\MessageBundle\Controller\UserMessagesListAwareController
    arguments:
      - '%template_paths.inbox%'
      - '%fos_message.pagination_limit%'
      - ['@fos_message.messages_inbox_provider.provider', 'getMessagesByParticipantOrderByDateAndIsReadStatus']

  fos_message.sent.controller:
    class: FOS\MessageBundle\Controller\UserMessagesListAwareController
    arguments:
      - '%template_paths.sent%'
      - '%fos_message.pagination_limit%'
      - ['@fos_message.messages_sent_provider.provider', 'getSentMessagesByParticipantOrderByDate']

  FOS\MessageBundle\Controller\ThreadCreateController:
    class: FOS\MessageBundle\Controller\ThreadCreateController
    arguments:
      - '%template_paths.new_thread%'
      - '@fos_message.new_thread_form.factory.default'
      - '@fos_message.new_thread_form.handler.default'

  FOS\MessageBundle\Controller\ThreadDeleteController:
    class: FOS\MessageBundle\Controller\ThreadDeleteController
    arguments:
      - '@fos_message.deleter.default'
      - '@fos_message.thread_manager.default'

  FOS\MessageBundle\Controller\ThreadDeletedController:
    class: FOS\MessageBundle\Controller\ThreadDeletedController
    arguments:
      - '@fos_message.provider.default'
      - '%template_paths.deleted%'

  FOS\MessageBundle\Controller\ThreadSearchController:
    class: FOS\MessageBundle\Controller\ThreadSearchController
    arguments:
      - '@fos_message.search_query_factory.default'
      - '@fos_message.search_finder.default'
      - '%template_paths.search%'

  FOS\MessageBundle\Controller\ThreadViewController:
    class: FOS\MessageBundle\Controller\ThreadViewController
    arguments:
      - '@fos_message.provider.default'
      - '%template_paths.view_thread%'
      - '@fos_message.reply_form.factory.default'
      - '@fos_message.reply_form.handler.default'

  FOS\MessageBundle\Controller\MessageAttachmentDownloadController:
    arguments:
      - '%fos_message.path_to_message_attachments_dir%'
      - '@doctrine.orm.entity_manager'
      - '%fos_message.message_attachment_class%'

  FOS\MessageBundle\Controller\ModerateMessageController:
    arguments:
      - '%fos_message.message_class%'
      - '%template_paths.moderate_message%'

  FOS\MessageBundle\Controller\ModerateMessageListController:
    arguments:
      - '%template_paths.moderate_message_list%'
      - 'moderate_messages_list'
      - 50
      - '@fos_message.moderate_message_list.provider'

  fos_message.moderate_message_list.provider:
    class: FOS\MessageBundle\Repository\MessageRepository
    arguments:
      - '@doctrine'

  fos_message.messages_inbox_provider.provider:
    class: FOS\MessageBundle\Repository\MessageRepository
    arguments:
      - '@doctrine'

  fos_message.messages_sent_provider.provider:
    class: FOS\MessageBundle\Repository\MessageRepository
    arguments:
      - '@doctrine'

